### PR TITLE
Feat: Shortcut to clear search bar

### LINKED ISSUE #241: Hotkey to clear navigation bar
As an ultra user, I want for the shortcut `ctrl`+`delete` to delete everything that's currently in the navigation bar, in order to save time

[4h]

### PR DESCRIPTION
**Pull request by FSadrieh**
- Resolves #241

### CODE REVIEW

**Comment by gwauge** [comment]
To get the new feature working, run `ALGCore initializeGlobalKeyBindings` in the workspace after pulling.

**Comment by gwauge** [comment]
Should probably be squashed before merging!

**Review by yannik-dittmar — COMMENTED** [review]
Looks good to me, but the actual command to update the keybindings is `ALGCore initializeGlobalKeyBindings`.

**Review by yannik-dittmar — APPROVED** [review]
If you want you can update the Readme/Wiki to mention the new Shortcut.

**Pull request merged**
